spring:
  application:
    name: bankwithdrawal-microservice
  config:
    import: configserver:http://192.168.101.7:8887
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

health:
  config:
    enabled=false:

logging:
  config:
  file: logback-spring.xml


